name: Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  metrics:
    runs-on: ubuntu-20.04
    steps:
      - name: Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: StrawberryCorps
          plugin_languages: yes
          plugin_traffic: yes
          plugin_lines: yes
      - name: Detailed report
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.pagespeed.detailed.svg
          token: NOT_NEEDED
          base: ""
          plugin_pagespeed: yes
          plugin_pagespeed_detailed: yes
          plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}
          plugin_pagespeed_url: https://strawberrycorps.github.io/
